# Generated by Django 2.2 on 2019-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwt', '0003_auto_20190502_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Answer'),
        ),
    ]
